version: '3.5'

networks: 
  as_network:
    driver: bridge

services:
  db:
    image: postgres:9.6-alpine
    container_name: as_db
    environment:
      - POSTGRES_DB=as_db
      - POSTGRES_USER=as_db_admin
      - POSTGRES_PASSWORD=1CvtaAolPQx
      - TZ=GMT
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "../migrations:/docker-entrypoint-initdb.d/"
    ports:
      - 4000:5432
    networks:
      - as_network

  db_test:
    image: postgres:9.6-alpine
    container_name: as_db_test
    environment:
      - POSTGRES_DB=as_db
      - POSTGRES_USER=as_db_admin
      - POSTGRES_PASSWORD=1CvtaAolPQx
      - TZ=GMT
    volumes:
      - "postgres_test:/var/lib/postgresql/data"
      - "../migrations:/docker-entrypoint-initdb.d/"
    ports:
      - 4100:5432
    networks:
      - as_network

  api:
    build:
      context: ../../api
      args:
        PGHOST: db
        PGHOST_TEST: db_test
        PGUSER: as_db_admin
        PGPASSWORD: 1CvtaAolPQx
        PGDATABASE: as_db
        JWT_SECRET: 5ufEcQ6UescTV9j7
        API_KEY: rSdx0w8ShgyK
    image: alo-sindico/as_api
    container_name: as_api
    ports:
      - "4002:4001"
    networks:
      - as_network
    depends_on:
      - db
      - db_test

volumes:
  postgres:
  postgres_test:


